// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5IMhXTip_E3XBlgovelD2kVoyTzI2SCg',
    appId: '1:549197052617:web:ce42ac576539ba04bdeb18',
    messagingSenderId: '549197052617',
    projectId: 'pulsar-7d45e',
    authDomain: 'pulsar-7d45e.firebaseapp.com',
    storageBucket: 'pulsar-7d45e.firebasestorage.app',
    measurementId: 'G-M02M303ZJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9uMa7iqNNmjVrvUP1OrzWMiOZpzrKZ4',
    appId: '1:549197052617:android:40e504b516207500bdeb18',
    messagingSenderId: '549197052617',
    projectId: 'pulsar-7d45e',
    storageBucket: 'pulsar-7d45e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuLmcgrnoMOc9QYbdLhUJMAsYz94YpjNk',
    appId: '1:549197052617:ios:64703950755c2d4dbdeb18',
    messagingSenderId: '549197052617',
    projectId: 'pulsar-7d45e',
    storageBucket: 'pulsar-7d45e.firebasestorage.app',
    iosBundleId: 'com.example.floweeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuLmcgrnoMOc9QYbdLhUJMAsYz94YpjNk',
    appId: '1:549197052617:ios:64703950755c2d4dbdeb18',
    messagingSenderId: '549197052617',
    projectId: 'pulsar-7d45e',
    storageBucket: 'pulsar-7d45e.firebasestorage.app',
    iosBundleId: 'com.example.floweeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5IMhXTip_E3XBlgovelD2kVoyTzI2SCg',
    appId: '1:549197052617:web:a2f3801fa7b25fcbbdeb18',
    messagingSenderId: '549197052617',
    projectId: 'pulsar-7d45e',
    authDomain: 'pulsar-7d45e.firebaseapp.com',
    storageBucket: 'pulsar-7d45e.firebasestorage.app',
    measurementId: 'G-B5HZGNKBH5',
  );

}